# Generated by Django 5.1.4 on 2024-12-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shortened',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=256)),
                ('shortCode', models.CharField(max_length=8)),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
            ],
        ),
    ]
