# Generated by Django 5.1.4 on 2024-12-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='shortened',
            name='updatedAt',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
