# Generated by Django 5.1.4 on 2024-12-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_shortenrequest_alter_shortened_updatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortened',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
